### ISSUE TITLE
Debugging doesn't start

### ISSUE THREAD

**Issue by treww** [actboy168/lua-debug#84]
There is nothing happens when I trying to debug lua file. 
Debuging panel appears for a moment and disappear. 
Neither debug nor run happens.

I have created a launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "lua_current",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${file}",
            "cwd": "${workspaceFolder}",
            "path": "${workspaceFolder}/?.lua",
            "cpath": "${workspaceFolder}/?.dll",
            "arg": [],
            "consoleCoding": "utf8"
        },
    ]
}
```

There is an error in console:
```
[2020-02-24 09:43:55.588] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///snap/code/25/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:728)
    at file:///snap/code/25/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:159
    at async t.RawDebugSession.shutdown (file:///snap/code/25/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2890:248)
```
VSCode:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-88-generic snap
```

**Comment by actboy168** [comment]
Add "console": "internalConsole" to launch.json and try again.

**Comment by treww** [comment]
I'am sorry but don't know what should change after adding 'internalConsole' where to look.
I have added 'internalConsole'. Have found these logs in the 'Log(ExtensionHost')
```
[2020-02-25 23:11:52.071] [exthost] [info] extension host started
[2020-02-25 23:11:52.089] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-02-25 23:11:52.089] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2020-02-25 23:11:52.096] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-02-25 23:11:52.096] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/emmet/dist/extension
[2020-02-25 23:11:52.113] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
[2020-02-25 23:11:52.113] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/git/dist/main
[2020-02-25 23:11:52.129] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-02-25 23:11:52.129] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/merge-conflict/dist/extension
[2020-02-25 23:11:52.130] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-02-25 23:11:52.130] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/search-result/dist/extension.js
[2020-02-25 23:11:52.131] [exthost] [info] ExtensionService#_doActivateExtension vscode.vscode-account {"startup":true,"extensionId":{"value":"vscode.vscode-account","_lower":"vscode.vscode-account"},"activationEvent":"*"}
[2020-02-25 23:11:52.131] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/vscode-account/dist/extension.js
[2020-02-25 23:11:52.177] [exthost] [info] eager extensions activated
[2020-02-25 23:11:53.508] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-server-ready {"startup":false,"extensionId":{"value":"vscode.debug-server-ready","_lower":"vscode.debug-server-ready"},"activationEvent":"onDebugResolve"}
[2020-02-25 23:11:53.508] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/debug-server-ready/dist/extension
[2020-02-25 23:11:53.509] [exthost] [info] ExtensionService#_doActivateExtension actboy168.lua-debug {"startup":false,"extensionId":{"value":"actboy168.lua-debug","_lower":"actboy168.lua-debug"},"activationEvent":"onDebugResolve:lua"}
[2020-02-25 23:11:53.509] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/treww/.vscode/extensions/actboy168.lua-debug-1.22.4/js/extension.js
[2020-02-25 23:12:07.579] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2020-02-25 23:12:07.579] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/configuration-editing/dist/extension
[2020-02-25 23:12:07.583] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-02-25 23:12:07.583] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/json-language-features/client/dist/jsonMain
[2020-02-25 23:12:07.614] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-02-25 23:12:07.614] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/typescript-language-features/dist/extension
```

In the console from Developer Tools I see next messages. One of which 'SIGPIPE' every time I start debug session.

```
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/usr/share/code/resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:200:13)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:728)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2892:159
    at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2890:248)
```

BTW. Everything happens on Ubuntu.

**Comment by actboy168** [comment]
It may be that lua-debug is not working.You can refer to the readme and recompile it.

**Comment by treww** [comment]
You are right. 
Recompiled luadebug on my machine and put into .vscode/extension. After that it again started to debug.

**Comment by cefn** [comment]
I hit this same issue and had to follow roughly the following steps from a blank debian install to populate a folder in the location `~/.vscode/extensions/lua-debug` which finally correctly debugged a lua program. My environment is debian buster running as a linux container within Chrome OS but would probably work for any modern debian or ubuntu.

First uninstall the Marketplace version of the Lua Debug package, then...

### Install some lua

```sudo apt install lua5.3```

### Install some versioning, compiling, making tools

```sudo apt install build-essential clang libreadline-dev git ninja-build```

### Check out and build luamake

```bash
cd ~
git clone https://github.com/actboy168/luamake
cd luamake
git submodule update --init --recursive
ninja -f ninja/linux.ninja
```

### Check out and build lua-debug

```bash
cd ~
git clone https://github.com/actboy168/lua-debug.git
cd lua-debug
git submodule update --init --recursive
../luamake/luamake
```

### Copy the resulting 'publish' folder to your vscode extensions folder as lua-debug

```
cd ~/lua-debug
cp publish ~/.vscode/extensions/lua-debug
```

Restart VSCode and find that `lua-debug` is now running and debugging code. My example working launch.json looks like...

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lua",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/example.lua"
        }
    ]
}
```
